name: CI for Sinatra Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # Adjust this to your project's Ruby version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          bundle install

      # Step 4: Run tests
      - name: Run tests
        run: |
          bundle exec rspec